Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: CI
+name: CI/CD Pipeline
 
 on:
   push:
@@ -20,12 +20,7 @@ jobs:
         uses: actions/setup-java@v2
         with:
           java-version: '17'  # Define a versão do JDK
-          distribution: 'temurin'  # Ou 'temurin', dependendo da sua preferência
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '20'  # Use a versão do Node.js que você está usando
+          distribution: 'temurin'
 
       - name: Install Docker
         run: |
@@ -45,21 +40,34 @@ jobs:
           sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
 
-      - name: Start Docker services
+      - name: Build with Maven
+        run: mvn clean install
+
+      - name: Pull Docker images with retry
         run: |
           cd wedelivery  # Mude para o diretório correto
-          docker-compose up -d  # Inicia os serviços em segundo plano
-          sleep 60
+          for i in {1..5}; do
+            docker-compose pull && break || sleep 10;
+          done
 
       - name: Deploy application
         run: |
           cd wedelivery  # Mude para o diretório correto
           make deploy  # Executa o comando make deploy
+          docker-compose up -d  # Inicia os serviços em segundo plano
+          sleep 60
 
       - name: Install dependencies
         run: |
           cd wedelivery-client  # Mude para o diretório correto
           npm install
+
+      - name: Check if services are running
+        run: |
+          if ! docker ps | grep -q 'your_service_name'; then
+            echo "Error: Docker service is not running!"
+            exit 1
+          fi
 
       - name: Run tests
         run: |
